name: number_trivia
description: A project for TDD training in flutter. Get the meaning of a number
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.1.0
  get_it: ^7.4.1
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  internet_connection_checker: ^1.0.0+1
  bloc: ^8.1.1
  flutter_native_splash: ^2.2.19
  html_unescape: ^2.0.0
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: 0.3.0
  flutter_launcher_icons: "^0.13.1"
  # flutter_native_splash: ^2.2.19

flutter_launcher_icons: #flutter pub run flutter_launcher_icons
  android: true
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash: # flutter pub run flutter_native_splash:create/remove
  color: "#FFFFFF"
  # background_image: "assets/background.png"
  image: assets/splash.png
  #branding: assets/dart.png
  #branding_mode: bottom
  color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png
  android_12:
    image: assets/splash.png

    # Splash screen background color.
    color: "#FFFFFF"

    # App icon background color.
    #icon_background_color: "#111111"

    # The branding property allows you to specify an image used as branding in the splash screen.
    #branding: assets/dart.png

    # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
    # apply when the device is in dark mode. If they are not specified, the app will use the
    # parameters from above.
    #image_dark: assets/android12splash-invert.png
    color_dark: "#042a49"
    #icon_background_color_dark: "#eeeeee"
  # android: false
  # ios: false
  web: false
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lang/
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
